### ISSUE TITLE
Why is `stylelint` not a dependency?

### ISSUE THREAD

**Issue by nategreen** [olegskl/gulp-stylelint#104]
I see that `stylelint` is a dev dependency of `gulp-stylelint` but it's not part of the `dependencies`. Why is that? (When I install only `gulp-stylelint`, I get a module load error when it looks for `stylelint`—which would seem to indicate that `stylelint` is _in fact_ a dependency, despite not being listed there.)

I do see where the docs say to install both packages, so I'm guessing there's some very good reason why it's omitted.

**Comment by olegskl** [comment]
Stylelint is a peer dependency. See discussion here: https://github.com/olegskl/gulp-stylelint/issues/35
