### ISSUE TITLE
warning " > gulp-stylelint@8.0.0" has incorrect peer dependency "stylelint@^9.6.0".

### ISSUE THREAD

**Issue by limonte** [olegskl/gulp-stylelint#110]
stylelint@10 has been released https://github.com/stylelint/stylelint/releases/tag/10.0.0

it would be nice to support it

**Comment by olegskl** [comment]
Released [9.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/v9.0.0) and published on npm. Thank you for opening this issue.
