### ISSUE TITLE
Using this as part of a regular CSS task vs a linting task

### ISSUE THREAD

**Issue by dan-gamble** [olegskl/gulp-stylelint#12]
My current CSS task looks like:

```
var paths = {
  src: path.join(config.root.src, config.tasks.css.src, '/*.' + config.tasks.css.extensions),
  dest: path.join(config.root.dest, config.tasks.css.dest)
}

var cssTask = function () {
  return gulp.src(paths.src)
    .pipe(sourcemaps.init())
    .pipe(postcss(require('../lib/postCssProcessors')))
    .on('error', console.log)
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream({match: '**/*.css'}))
}
```

When i change it like:

```
var paths = {
  src: path.join(config.root.src, config.tasks.css.src, '/*.' + config.tasks.css.extensions),
  dest: path.join(config.root.dest, config.tasks.css.dest)
}

var cssTask = function () {
  return gulp.src(paths.src)
    .pipe(stylelint({
      configFile: './stylelint.config.js'
    }))
    .pipe(sourcemaps.init())
    .pipe(postcss(require('../lib/postCssProcessors')))
    .on('error', console.log)
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream({match: '**/*.css'}))
}
```

The CSS task when it is ran through the `default` task just seems to hang, when i remove the `stylelint()` part it goes back to being fine, is there something i'm missing or can it not be part of the compilation step?

The reason i want it part of the compilation step is because i already do have a separate `stylelint` task but Gulp is really intermittent with running that so i was gonna look to see if i can have it as part of the compilation task as that gets ran all the time instead of having it as a dependancy of the CSS task as the dependancy only gets run around 10% of the time. I know it's a deeper lying problem with my Gulp set up but i was looking to use this way as an interim step :)

**Comment by olegskl** [comment]
First of all thank you for taking your time to report an issue. Much appreciated!

I'm not sure if `stylelint` in your example refers to [`stylelint`](https://github.com/stylelint/stylelint) or [`gulp-stylelint`](https://github.com/olegskl/gulp-stylelint) :sweat_smile: 

Assuming it refers to `gulp-stylelint`, I would like to point out that the following code will attempt to fail your gulp task with a non-zero exit code, so if you pipe it into something else you either need to set [`failAfterError`](https://github.com/olegskl/gulp-stylelint#failaftererror) option to false, or add an error event handler just like you do it for postcss in your example above.
```js
.pipe(gulpStylelint({
  configFile: './stylelint.config.js'
}))
```

Also, it will not generate any interesting output. You need to specify a [formatter](https://github.com/olegskl/gulp-stylelint#formatters) to see meaningful reports.

I've marked this as a bug because while testing I noticed that gulp-stylelint would block long running tasks upon encountering a linting error. I'm hoping that #13 corrects the issue. Below is the gulp config file that I used to test the fix:

```js
var gulp = require('gulp');
var gulpStylelint = require('gulp-stylelint');
var browserSync = require('browser-sync').create();

gulp.task('css', function () {
  return gulp.src('foo.css')
    .pipe(gulpStylelint({
      // <-- ideally you need reporters here
      // failAfterError: false // <-- recommended in this scenario instead of the error
                               //     handler on the next line
    }))
    .on('error', function (e) { console.log(e.message); })
    // if you don't provide an error handler and don't set failAfterError option to false,
    // then the task will fail with non-zero error code
    .pipe(gulp.dest('styles'))
    .pipe(browserSync.stream());
});

gulp.task('serve', ['css'], function(cb) {
  browserSync.init({server: './'});
  gulp.watch('foo.css', ['css'], cb);
});
```

Running `gulp serve` 

```sh
test ➤ gulp serve
[20:17:29] Using gulpfile ~/repos/test/gulpfile.js
[20:17:29] Starting 'css'...
[20:17:29] Finished 'css' after 62 ms
[20:17:29] Starting 'serve'...
[BS] Access URLs: ... # [skipped for brevity]
[BS] Serving files from: ./ # A browser page opens...

# Now I introduce a lint error in my css file...

[20:17:33] Starting 'css'...
Errors were found while linting code. # <-- error handler logged this
[BS] 1 file changed (foo.css)
[20:17:33] Finished 'css' after 19 ms

# Now I fix the lint error in the css file...

[20:17:34] Starting 'css'...
[BS] 1 file changed (foo.css)
[20:17:34] Finished 'css' after 9.78 ms
```

**Comment by dan-gamble** [comment]
Wow this is awesome, thanks! I'll check out out soon and give feedback on what i find :)

**Comment by dan-gamble** [comment]
This worked perfectly 👍  Not quite sure what i was doing as i had previously had the `reporters` too it just wasn't included in my example. Maybe it was the #13 fix as my main problem was the hanging :)

1 final question! Is there a way to use [postcss-reporter](https://github.com/postcss/postcss-reporter) with this? I prefer the output of that as opposed to the simple string way :)

**Comment by olegskl** [comment]
I'm glad it worked for you.

The "string" formatter [actually uses](https://github.com/stylelint/stylelint/blob/master/src/formatters/stringFormatter.js#L3) postcss-reporter behind the scenes. So it's basically the same thing. The only difference is that [it sets](https://github.com/stylelint/stylelint/blob/master/src/formatters/stringFormatter.js#L5-L8) `noIcon` and `noPlugin` options to `true`.

**Comment by dan-gamble** [comment]
What i currently have is:

![output](https://i.imgur.com/TwtVDyR.png)

The top is using `gulp-stylelint` and the bottom is using:

```js
var styleLintTask = function () {
  var processors = [
    require('stylelint'),
    reporter({clearMessages: true})
  ]

  return gulp.src(paths.src)
    .pipe(postcss(processors))
}
```

Which now i look at it seems to imply `noIcon` and `noPlugin` are off looking at the differences. Is there a way to turn them on in the `formatter` options?

**Comment by olegskl** [comment]
Currently the embedded stylelint formatter (which is used by gulp-stylelint) doesn't allow for such a configuration. The values are basically hard-coded. I don't know if there's any specific reason why those options were set to `true`. You might want to open an issue on the [stylelint](https://github.com/stylelint/stylelint) repository about that.

**Comment by dan-gamble** [comment]
Fair enough! Thanks for all your help, you can consider this closed if you are satisfied your end as well :).

**Comment by olegskl** [comment]
Thanks to you for finding and reporting the bug! :smile: :+1:
