### ISSUE TITLE
Update to stylelint 12.0

### ISSUE THREAD

**Issue by khalyomede** [olegskl/gulp-stylelint#122]
Just got an alert that stylelint has moved to [version 12](https://github.com/stylelint/stylelint/tree/12.0.0). Do you mind upgrading please?

Great plugin :)

**Comment by ffaubert** [comment]
Bump

**Comment by olegskl** [comment]
Done in [v11.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/11.0.0).
