### ISSUE TITLE
Print summary

### ISSUE THREAD

**Issue by gor0n** [olegskl/gulp-stylelint#30]
Hi,

Is there a way to get a summary with a counter for all errors and warnings in all linted files? We are building a frontend starter kit at my agency and we need to print a summary (we also need to pass this summary to gulp-notify).

I was able to build a summary with gulp-eslint with eslint.results() but I can't find a similar way with gulp-stylelint.

I can build a summary myself but I need a way to know if there is a error or warning in a file. Right now, I'm not able to find that information in my gulp stream.

**Comment by olegskl** [comment]
Hello,

 1. You can print a custom summary by creating a [custom formatter](https://github.com/olegskl/gulp-stylelint#formatters). It takes stylelint results object and should return a string. gulp-stylelint will then write it to console or to a file (or both), depending on the options you provide.

 2. I'm not so sure if you can make it work with gulp-notify as gulp-stylelint does not currently pipe stylelint results down the gulp stream.

**Comment by gor0n** [comment]
Thanks for your answer! Indeed I think it's my solution.

But how can I get the array of stylelint result objects to pass to my custom formatter?
Here it's named input https://github.com/stylelint/stylelint/issues/659 but it doesn't seem the same in gulp-stylelint.

**Comment by olegskl** [comment]
You can get some inspiration from the [checkstyle formatter](https://github.com/davidtheclark/stylelint-checkstyle-formatter/blob/master/index.js). 

Below is an example of a custom formatter that returns the beautified JSON of stylelint result objects. Here gulp-stylelint will output the result to console.

```js
gulp
  .src('src/**/*.css')
  .pipe(gulpStylelint({
    reporters: [{
      formatter: function (stylelintResults) {
        return JSON.stringify(stylelintResults, null, '  ');
      },
      console: true
    }]
 }));
```
