### ISSUE TITLE
Indentation error in SASS maps

### ISSUE THREAD

**Issue by cyril-lamotte** [olegskl/gulp-stylelint#34]
Hi, thank you for your work

Since some days, that notation is giving indentations errors (SASS) : 

```scss
// SASS map
$breakpoints: (
  '0' : 0,
  'xs': 480,
  'sm': 768,
  'md': 992,
  'lg': $max-site-width-int
);
```

```
 22:3  ×  Expected indentation of 0 spaces   indentation
 23:3  ×  Expected indentation of 0 spaces   indentation
 24:3  ×  Expected indentation of 0 spaces   indentation
 25:3  ×  Expected indentation of 0 spaces   indentation
 26:3  ×  Expected indentation of 0 spaces   indentation
```

Is-it a regression ?

**Comment by olegskl** [comment]
This looks like a [stylelint](https://github.com/stylelint/stylelint) issue. gulp-stylelint doesn't do any  linting itself.

**Comment by cyril-lamotte** [comment]
Ok thanks I'll go there

Cyril Lamotte

2016-07-22 10:28 GMT+02:00 Oleg Sklyanchuk <notifications@github.com>:
