### ISSUE TITLE
Update to stylelint 7.1

### ISSUE THREAD

**Issue by thasmo** [olegskl/gulp-stylelint#37]
Lots of bugfixes and more. ;)

**Comment by olegskl** [comment]
Done.

I've also set up [greenkeeper](https://greenkeeper.io/) that will automatically create merge requests when new versions of dependencies are released.

**Comment by thasmo** [comment]
Awesome! :)

**Comment by thasmo** [comment]
@olegskl You didn't tag the release on GitHub. On purpose?

**Comment by olegskl** [comment]
Facepalm... my bad, it's [done](https://github.com/olegskl/gulp-stylelint/releases). I did publish on npm, but forgot to push tags to github. Apologies.

**Comment by thasmo** [comment]
No prob!
