### ISSUE TITLE
Use stylelint's Node API instead of PostCSS plugin

### ISSUE THREAD

**Issue by davidtheclark** [olegskl/gulp-stylelint#4]
stylelint has a standalone Node API, and I think it would be preferable for this plugin to use that, instead of running PostCSS and using stylelint as a PostCSS plugin. There are features available in the Node API that users of gulp-stylelint would definitely want, like the ability to set `syntax: scss`.

Additionally, the Node API was really *built for* this kind of thing; so if there's a reason it doesn't work for you, I'd appreciate the feedback and I'll see if I can improve it :)

**Comment by olegskl** [comment]
I have previously considered using the stylelint API directly, but there was no option for setting the syntax and (maybe I was just too lazy to properly search for it).

**Comment by davidtheclark** [comment]
http://stylelint.io/user-guide/node-api/#syntax

**Comment by davidtheclark** [comment]
Oh, maybe I misunderstood the comment ... yeah, we've been adding features at a pretty fast pace.

**Comment by olegskl** [comment]
I've created a PR #5 that uses the stylelint API. The feedback is welcome if you have time.

**Comment by davidtheclark** [comment]
Cool. I will definitely try to take a look within the next day or two.

**Comment by olegskl** [comment]
Version [1.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/1.0.0) now uses stylelint's node API, so I believe this issue can now be closed. Thank you for your advice and contribution!
