### ISSUE TITLE
No configuration found - Code 78

### ISSUE THREAD

**Issue by basilio** [olegskl/gulp-stylelint#40]
Perhaps similar to the closed issue https://github.com/olegskl/gulp-stylelint/issues/18
I'm using the latest release 3.1.0

```
Message:
    No configuration found
Details:
    code: 78
```

**Comment by olegskl** [comment]
You need to have some sort of configuration prior to running stylelint or gulp-stylelint. It could be in a file (see [user-guide/configuration](http://stylelint.io/user-guide/configuration/)) or as a `config` property in gulp-stylelint options object, (see [sample config](https://github.com/olegskl/gulp-stylelint-test/blob/master/gulpfile.js)).

**Comment by basilio** [comment]
Works great! Thanks
