### ISSUE TITLE
Update to stylelint 7.2

### ISSUE THREAD

**Issue by chaficnajjar** [olegskl/gulp-stylelint#41]
Just wanted to bring to your attention that a [new version of stylelint](https://github.com/stylelint/stylelint/releases/tag/7.2.0) has been released.

Thank you for maintaining this Gulp plugin :)

**Comment by olegskl** [comment]
[Done](https://github.com/olegskl/gulp-stylelint/releases/tag/3.2.0) and [published](https://www.npmjs.com/package/gulp-stylelint).

**Comment by chaficnajjar** [comment]
That was fast, thanks!
