### ISSUE TITLE
Not working correctly when watching

### ISSUE THREAD

**Issue by thomasmattheussen** [olegskl/gulp-stylelint#51]
Seem to remember having had this issue some time ago, but can't find any related issues, so..

It seems to me that the plugin doesn't work correctly when watching _"many"_ files. 

When starting my watch process, I see the stylelint output in the console the first time. But when saving, and thus retriggering `gulp-stylelint`, I don't get any linter output no more. 

I have tried debugging this, and it seems to me that it's got something to do with the number of files to process. When watching a significantly smaller set of files, everything works like a charm.

**Comment by olegskl** [comment]
Hello. I've been trying to reproduce the issue and failed. I've added `npm run lint-live` to [gulp-stylelint-test](https://github.com/olegskl/gulp-stylelint-test) repository which contains 500 scss files. It seems to work fine.

Perhaps you have `failOnError: true` (this is by default) in gulp-stylelint config and it breaks the pipe? In this case you can either disable the `failOnError` option or handle errors on pipeline level. See [pipeline error management](https://gulp.readme.io/docs/combining-streams-to-handle-errors) in Gulp.

Also, I know I'm replying very late... shame on me 😭

**Comment by thomasmattheussen** [comment]
Hmmm,

I'm guessing you mean `failAfterError` (instead of `failOnError`) ? That doesn't seem to be the problem, already had it set to false... I will try to dig deeper then :/

No problem with the "late" reply by the way, we all have our lives ;)

**Comment by thomasmattheussen** [comment]
I'm wondering, could it be related to the fact that I'm using gulp-watch? 

When trying to debug what was going on, I noticed that onStreamEnd doesn't get called when watching... (https://github.com/olegskl/gulp-stylelint/blob/master/src/index.js#L154)

I found this issue https://github.com/floatdrop/gulp-watch/issues/164 and am thinking it's somehow relatable?

**Comment by olegskl** [comment]
Indeed, I meant `failAfterError`.
It should be working the same with gulp-watch, but I will double-check tonight. If you have a repository I could checkout - I will take a look at it too.

**Comment by thomasmattheussen** [comment]
Unfortunately I don't have a public repo :/

Could it have anything to do with the fact that `gulp-watch` never emits an `end` because it creates an infinite stream?

That's what I'm trying to find out now...

**Comment by olegskl** [comment]
I don't think so, but I will investigate.

**Comment by thomasmattheussen** [comment]
I have based my code on https://github.com/vigetlabs/gulp-starter , basically extended it by adding stylelint to it. The important bits should be these:

tasks/stylelint.js

```js
const
    config = require('../config'),
    gulp = require('gulp'),
    stylelint = require('gulp-stylelint'),
    path = require('path'),
    paths = {
        src: path.join(config.root.src, config.tasks.stylelint.src, '/**/*.{' + config.tasks.stylelint.extensions + '}')
    },
    stylelintTask = () => {
        return gulp.src([paths.src])
            .pipe(stylelint({
                failAfterError: global.production ? true : false,
                reporters: [{
                    formatter: 'string',
                    console: true
                }]
            }));
    };

gulp.task('stylelint', stylelintTask);
module.exports = stylelintTask;
```

tasks/watch.js


```js
const
    config = require('../config'),
    gulp = require('gulp'),
    path = require('path'),
    watch = require('gulp-watch'),
    watchTask = () => {
        const watchableTasks = ['images', 'svgSprite', 'templates', 'css', 'eslint', 'stylelint'];

        watchableTasks.forEach((taskName) => {
            const task = config.tasks[taskName];
            if (task) {
                const glob = path.join(config.root.src, task.src, '**/*.{' + task.extensions.join(',') + '}');
                watch(glob, () => {
                    require('./' + taskName)();
                });
            }
        });
    };

gulp.task('watch', ['browserSync'], watchTask);
```

**Comment by thomasmattheussen** [comment]
This repo has become public as luck may have it and should be available at https://git.prophets.be/open-source/dameblanche

To run it, just 

clone it
$ npm (or yarn) install
$ npm run start

The issue should prop up when introducing a linting-error (as in, stylelint won't notify of the error)

as opposed to when running

$ npm run start stylelint

Now, the linting-error should show.

**Comment by olegskl** [comment]
Why are you not calling gulp tasks on change?

**Comment by olegskl** [comment]
Please try the 4.0.0.

**Comment by thomasmattheussen** [comment]
Yep, that works! Thanks!

Out of curiosity, is there something "wrong" (or unconventional) with my approach? What do you mean by "not calling gulp tasks on change" (I thought I was doing that...)

**Comment by olegskl** [comment]
Well, you're calling the task function, not the task itself. There is a difference, because the task wraps the function in some additional stuff. Here's how I used to do it when working with Gulp: `gulp.watch('*.css', ['lint:css'])` or, if you're using gulp-watch: `gulpWatch('*.css', () => runSequence('lint:css'));`

Glad that 4.0.0 worked for you.

**Comment by thomasmattheussen** [comment]
Hmmm, yeah, I can see that. I guess I thought that explicitly returning ```gulp.src(...).pipe(...)``` would have solved that. Seem to think I read that somewhere. 

Anyway, thanks again! ;)
