### ISSUE TITLE
Update for Stylelint 7.6.0?

### ISSUE THREAD

**Issue by danimalweb** [olegskl/gulp-stylelint#53]
My stylelint-config-standard v15 depends on stylelint 7.6.0.

Any chance of getting gulp-styelint updated to use this new version (7.6.0)?

Thanks.

**Comment by ntwb** [comment]
It looks like @greenkeeperio-bot missed the stylelint v7.6.0 release

**Comment by ntwb** [comment]
That said, `gulp-stylelint` should support stylelint v7.6.0 perfectly as is, it has a semantic version dependency of `"stylelint": "^7.4.2",`, `7.6.0` is covered by `^7.4.2`.

You check semver coverage here as an FYI https://semver.npmjs.com

@danimalweb Running `npm update` should get things sorted for you 😄

**Comment by danimalweb** [comment]
Thanks. I thought that would be the case, but removing node_modules, cleaning npm cache and re-installing / updating the issue continues.

It's must be a conflict with [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) then. For now, I've added  ``"stylelint": "^7.6.0"`` directly into my package.json.to reslove the issue.

Cheers.

**Comment by olegskl** [comment]
Updated and published as v3.5.0 to npm. Sorry for delays... life's busy.
