### ISSUE TITLE
Can't find formatters with current stylelint master

### ISSUE THREAD

**Issue by jwilsson** [olegskl/gulp-stylelint#57]
Hi,
Thanks for your hard work on this!

I just tried running this on one of my projects as a part of testing out the `master` branch of `stylelint` (since it contains some [pretty major internal changes](https://github.com/stylelint/stylelint/pull/2134)).

However, `gulp-stylelint` crashed immediately because the formatters doesn't reside in `stylelint/dist/formatters` anymore (they're in `stylelint/lib/formatters` now).

I filed an [issue](https://github.com/stylelint/stylelint/issues/2181) about exposing a `formatters` property over at the main `stylelint` project and I'd be happy to make any changes necessary here as well (either just changing the path or using a new `formatters` property if that's accepted).

Cheers,
Jonathan

**Comment by olegskl** [comment]
Awesome! Contributions are welcome \(^_^)/

**Comment by olegskl** [comment]
Published in 3.7.0

**Comment by notethis** [comment]
Hi. I'm still seeing this issue when I run 3.7.0 in conjunction with stylelint@7.70

@olegskl @jwilsson any throughts on resolving it?

**Comment by olegskl** [comment]
Hello @notethis. Can you provide the error message?

**Comment by notethis** [comment]
Ah! @olegskl  NPM was still installing 3.4.0 for some odd reason due to a dependency. It works now that I told that dependency to use 3.7.0.  Thanks!
