### ISSUE TITLE
When it emits an error the whole gulp stream crashes and doesn't watch anymore

### ISSUE THREAD

**Issue by marcofugaro** [olegskl/gulp-stylelint#60]
I am using a `gulp-stylelint` task with `run-sequence` like this
```js
runSequence(['markup', 'stylelint', 'styles', 'eslint', 'browserify', 'images', 'fonts'], 'watch', cb);
```
and when stylelint fails also the run-sequence stream fails freezing and not watching anymore, this is what I get, see how it emit an error two times:
![](http://i.imgur.com/KKKlCWe.png)

Maybe the problem is not returning an actual stream like gulp-eslint does instead of calling `done`?

Anyway here is my gulp task https://github.com/marcofugaro/gulp-frontend-boilerplate/blob/master/tasks/stylelint.js

**Comment by olegskl** [comment]
Hello! Thanks for taking your time to report this.

I have trouble reproducing this. I have cloned your repository (commit [96696ea](https://github.com/marcofugaro/gulp-frontend-boilerplate/commit/96696ea6317886c50be5ab825a26fe6611b7eb7b)), installed dependencies and run `gulp dev`. It found issues in 5 CSS files. I then changed those files several times. The watcher seems to be working fine (picks up new changes, reports issues).

I have tried the above on Node 4, 6, 7 on OSX.

Do you have a branch I could checkout to reproduce it?
Could be related to #51.

**Comment by marcofugaro** [comment]
Yup, just comment out this line, and run `gulp dev`

https://github.com/marcofugaro/gulp-frontend-boilerplate/blob/master/tasks/stylelint.js#L23

Sorry for not pointing out this before.

**Comment by olegskl** [comment]
Okay. I see. However, correct me if I'm wrong, but if you comment out [this line in eslint.js](https://github.com/marcofugaro/gulp-frontend-boilerplate/blob/96696ea6317886c50be5ab825a26fe6611b7eb7b/tasks/eslint.js#L22) then you'll have exactly the same problem with gulp-eslint.

What you can do is emit an "end" event like so:

```js
.pipe(...)
.on('error', function (error) {
  notify.onError({
    title: 'Error linting scripts!', // or 'Error linting styles!'
    message: error.message,
  })(error);
  this.emit('end'); // <--- this!
});
```

You might be interested in these resources:
 - https://github.com/gulpjs/gulp/issues/259
 - http://stackoverflow.com/questions/21602332/catching-gulp-mocha-errors

**Comment by marcofugaro** [comment]
Yup, correct. Thanks for the resources, so I suppose this is no issue with gulp-stylelint.

**Comment by olegskl** [comment]
I'm not an expert, but it seems that this is how Gulp 3.x works. This behavior is changing in 4.x and gulp-plumber will become obsolete when it's finally released.

**Comment by marcofugaro** [comment]
Yeah can't wait for it, it's difficult to write beautiful code with gulp 3, also finally `run-sequence` will become obsolete in favor of `series` and `parallel`!

**Comment by thymikee** [comment]
Can confirm that this happens on 3.6.
Works as expected in 3.5 and below, so I had to fix the version of this dep.

Sample task: 
```js
gulp.task('lint-css', function() {
    return gulp.src(path.join(config.src.base, config.src.styles))
      .pipe(plugins.stylelint({
        reporters: [
          {formatter: 'string', console: true}
        ]
      }));
  });
```

**Comment by olegskl** [comment]
@thymikee Hello, I don't think your issue is related to the current thread. I have opened #62 instead.
