### ISSUE TITLE
Update to stylelint 7.8.0

### ISSUE THREAD

**Issue by daveaspinall** [olegskl/gulp-stylelint#68]
We've had to update to `stylelint-config-standard@^16.0.0` to fix some deprecated rules, which requires `stylelint@^7.8.0`.

Please could you update it? Sorry I've seen quite a few of these requests for previous versions, hope I'm not being annoying!

Thanks!

**Comment by Ne-Ne** [comment]
Just done a pull request (https://github.com/olegskl/gulp-stylelint/pull/69)
