### ISSUE TITLE
stylelint caching

### ISSUE THREAD

**Issue by woble** [olegskl/gulp-stylelint#75]
Stylelint added caching in `7.10.0` (Ref: https://github.com/stylelint/stylelint/pull/2293). Can it be enabled through `gulp-stylelint`?

**Comment by olegskl** [comment]
Hello. Unfortunately, the tests do not pass with 7.10.1. This is probably a bug in stylelint.

**Comment by olegskl** [comment]
Not planning to use stylelint's caching. Caching should be done on gulp level.

**Comment by ZhangChengLin** [comment]
https://github.com/olegskl/gulp-stylelint/pull/127
