### ISSUE TITLE
Make package CommonJS friendly

### ISSUE THREAD

**Issue by davidtheclark** [olegskl/gulp-stylelint#8]
It's weird to me that the package does `export default` and the examples use ES2015 `import` syntax when that is not actually supported by Node. I think most Node users would be using `require()`, so in my mind it makes sense to export in such a way that users don't have to `var gulpStylelint = require('gulp-stylelint').default;` but can just `require('gulp-stylelint')`; and to write examples with CommonJS. Do you disagree?

**Comment by olegskl** [comment]
This has been released in [1.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/1.0.0). Feel free to re-open the issue if necessary. Thank you for your advice and contribution!

**Comment by davidtheclark** [comment]
Fantastic! Looks really good. I hope people use this as a model for grunt etc. plugins.
