### ISSUE TITLE
Not Correctly Linting Blobs

### ISSUE THREAD

**Issue by chryton** [olegskl/gulp-stylelint#81]
Given this basic gulp setup:

```
gulp.src('src/css/scss/**/*.scss')
	.pipe(stylelint({
		failAfterError: true,
		reportOutputDir: "reports/",
		reporters: [
			{ formatter: 'verbose', console: true},
			{ formatter: 'json', save: 'report.json'}
		],
		debug: true
	}));
```

and this folder structure:

```
src
├── css
│   └── scss
│       ├── base
│       │   ├── bourbon
│       │   └── libs
│       ├── legacy
│       ├── modules
│       │   └── pages
│       ├── style-guide
│       └── styles.scss
└── js
```

and ever folder within `src/css/scss` has at least one `_file.scss` within it, `gulp-stylelint` does not go more than one level deep to find files to lint. So, in this case it only lints `styles.scss` rather than allt he files within the `scss/` directory.

**Comment by chryton** [comment]
I should also note that the CLI consumes the same blob correctly and outputs linting results for all the files within the director.

**Comment by olegskl** [comment]
I'm unable to reproduce.

**Comment by chryton** [comment]
I can offer a screen recording if that is helpful

**Comment by olegskl** [comment]
Can you create a small reproducible example? You can fork this one: https://github.com/olegskl/gulp-stylelint-test

**Comment by chryton** [comment]
@olegskl Here ya go: https://github.com/chryton/stylelint-test

**Comment by olegskl** [comment]
Okay, I see. What you need to do is **return the `gulp.src` stream in your task function**. The gulp-stylelint library collects and lints all files that pass through the stream until the stream is closed. This is how it knows that there are no more files to process. If you never return the stream, it will never close.

Also, because the linting is asynchronous, you need to `gutil.log()` when the `'end'` event is called.

So you should try something like this:

```js
gulp.task('css:postsass', function () {
  gutil.log(gutil.colors.blue('--> LINTING SCSS'));
  return gulp.src('src/css/scss/**/*.scss')
    .pipe(gulpStylelint({...}))
    .on('end', function () {
      gutil.log('--> THE PAIN OF LINTING IS COMPLETE');
    });
});

**Comment by chryton** [comment]
Ah, interesting. Some of the other hinting/linting plugins don't require returning the stream so I assumed it wasn't required here. Thanks for the help!
