### ISSUE TITLE
Update Stylelist Version 7.11.0 -> Feature fix: true

### ISSUE THREAD

**Issue by assadtony** [olegskl/gulp-stylelint#82]
It's my first time using gulp-stylelint and I want to thank you guys, its great.

I am using the latest version and encountering a problem with the new --fix and fix: true command from Stylelist.

Is an update for Stylelist Version 7.11.0 coming soon?

It seems that the 'fix: true' command does the fix but does not return it to the stream to get it saved properly.

Here is my gulp command:
gulp.task('format-stylelint', function() {
    return gulp.src(sourcePaths.styles)
        .pipe(plumber({errorHandler: notify.onError("SASS Lint Error: <%= error.message %>")}))
        .pipe(stylelint({
            config: {
              extends: 'stylelint-config-standard',
              rules: {
                "indentation": "tab"
              },
              fix: true
            },
            fix: true,
            reporters: [
              {formatter: 'verbose', console: true}
            ],
            failAfterError: false
        }))
        .pipe(gulp.dest( distPaths.sass ))
});

I do see in the terminal the number of errors drop drastically but when saving back the files and comparing both folders, I get the same files (no changes made).

**Comment by klimashkin** [comment]
The same issue, it fixes file but doesn't return fixed version to the stream

**Comment by amazingSurge** [comment]
We need 7.11.0 too. Please add the fix option. Thanks.

**Comment by olegskl** [comment]
@assadtony @klimashkin I'm afraid it is impossible to return the fixed version to the stream using stylelint 7.12 because it writes the file directly on disk and doesn't actually output the fixed content.

@amazingSurge You can `npm --depth 1 update gulp-stylelint` to use the latest 7.x version of stylelint without waiting for gulp-stylelint releases.

**Comment by olegskl** [comment]
I have opened an issue on stylelint repo: https://github.com/stylelint/stylelint/issues/2710

**Comment by yongzhihuang** [comment]
thanks @olegskl definitely would like to see this working soon.

**Comment by olegskl** [comment]
It seems that https://github.com/stylelint/stylelint/commit/ac7c141df085a1042604812cec98b901b9744ce3 fixes the issue. Still in master though.

**Comment by mismith** [comment]
Any update on this? I wanna pull stylelint out of CLI and into Gulp, but we'd be losing the ability to `fix` with the current implementation.

Does stylelint v8.0.0 support outputting streams yet? Can I help with a PR?
FWIW, might this be useful: https://github.com/adametry/gulp-eslint/blob/master/index.js#L66 (`gulp-eslint`'s implementation of `fix`)

**Comment by olegskl** [comment]
@mismith stylelint supports `fix` option for strings since [8.3.0](https://github.com/stylelint/stylelint/releases/tag/8.3.0). There's https://github.com/olegskl/gulp-stylelint/pull/87 you can follow for updates related to this option.

**Comment by mismith** [comment]
Awesome #87 looks great. Here's hoping it get merged soon :)

**Comment by olegskl** [comment]
Published in [6.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/6.0.0)
