### ISSUE TITLE
Remove gulp-util as dependency

### ISSUE THREAD

**Issue by webuxr** [olegskl/gulp-stylelint#93]
"Help us fix the ecosystem
Using these steps, you can help plugin authors migrate away from gulp-util."

Following along with https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 I'm seeing the following dependency tree after running `npm ls gulp-util`:

```
me@0.0.1 /Users/me
└─┬ gulp-stylelint@3.9.0
  └── gulp-util@3.0.8
```
Does `gulp-stylelint` really need to depend upon `gulp-util`?

**Comment by webuxr** [comment]
FYI: See also https://github.com/gulpjs/gulp-util/pull/102

**Comment by olegskl** [comment]
Hello. I'm not planning to maintain old versions of gulp-stylelint. You might want to upgrade. The [version 6.0.0](https://github.com/olegskl/gulp-stylelint/releases/tag/6.0.0) released today does not include gulp-util thanks to the contribution of @TheDancingCode in cb3780c63306435d5e38a0345fe5a4ff6b62b27e, see [package.json](https://github.com/olegskl/gulp-stylelint/blob/master/package.json).

**Comment by webuxr** [comment]
Thanks for the lightning-fast response @olegskl ... much appreciated.
