### ISSUE TITLE
`node_modules` not ignored

### ISSUE THREAD

**Issue by coreybruyere** [olegskl/gulp-stylelint#98]
Thanks for the plugin.

I'm using gulp-stylelint and receiving linting errors on src files found in a node_modules folder that's not in the root of my folder. I specified `ignorePath` in the task options but haven't been able to get it working. This is what I'm currently working with:

```
gulp.task('stylelint', () => {
  gulp.src('assets/stylesheets/**/*.scss')
    .pipe(gulpStylelint({
      config: stylelintConfig,
      failAfterError: false,
      ignorePath: 'assets/stylesheets/node_modules/inuitcss/**/*.scss',
      reporters: [
        { formatter: 'string', console: true },
      ],
    }));
});
```

I've also specified a value to the `ignoreFiles` option in my .stylelintrc.json without any success. The plugin is working as intended on other src files (`assets/stylesheets/**/*.scss`) 

🤔

**Comment by olegskl** [comment]
Hello @coreybruyere. Unfortunately, ignoring doesn't work due to some issues with stylelint Node API. You can however ignore the unwanted files in the glob you pass to `gulp.src`.

**Comment by coreybruyere** [comment]
Got it working. Thanks!
