### ISSUE TITLE
Can't get autofix to work

### ISSUE THREAD

**Issue by subtlegusto** [olegskl/gulp-stylelint#99]
Eventually, I would like for gulp-stylelint to fix our source .scss files on save. For now, I'm just trying to get syntax rules corrected using one plain .css file. When this runs, the indentation error does output to the console, but the .css file is not corrected.

I have run this through the stylelint CLI using `$ stylelint "src/styles/*.css" --fix` and it worked.

.stylelintrc
```
{
  "rules": {
    "indentation": 2
  }
}
```

gulpfile.js
```
gulp.task('styles:lint', function lintCssTask() {
  return gulp.src([
      './src/styles/*.css'
    ])
    .pipe(stylelint({
      fix: true,
      reporters: [{
        formatter: 'string',
        console: true,
      }],
      failAfterError: false,
    }))
    .pipe(gulp.dest('./src/styles'));;
});
```

CSS
The below rule uses 4-space indentation, which should be corrected to 2 spaces.
```
.blah {
    color: black;
}
```

The `--fix` flag was [added in stylelint 7.11.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#7110). My global stylelint is v9.1.3. The version installed by gulp-stylelint is 8.2.0, so I don't think this is a version problem.

I'm running Node v8.9.4 and NPM v5.7.1.

**Comment by olegskl** [comment]
Hello! Which version of gulp-stylelint are you using? The latest versions don't come with stylelint preinstalled, so you're probably on version 5, which doesn't have the fix option enabled.

**Comment by subtlegusto** [comment]
RIght you are. We had installed gulp-stylelint several months ago and I'm back testing it now. I've updated to the latest version and autofix is working. Thank you!

**Comment by MatTeague** [comment]
Hi, I'm having the same issue. I can't get gulp-stylelint to autofix my scss files. When I run the CLI it fixes all issues. However, when I run gulp-stylelint I get:

```
mat@Mats-MacBook-Pro kube (development) $ gulp scsslinting
[15:26:36] Failed to load external module @babel/register
[15:26:36] Requiring external module babel-register
[15:26:39] Using gulpfile ~/Sites/mamp/steelvintage/wp-content/themes/kube/gulpfile.babel.js
[15:26:39] Starting 'scsslinting'...
[15:26:39] Finished 'scsslinting' after 433 ms
```
With the errors still there.

My Gulp task is:

```js
export const scsslinting = () => {
	return src('.src/scss/**/*.scss')
		.pipe($.plumber())
		.pipe($.changed('./src/scss'))
		.pipe($.stylelint({
			fix: true,
			reporters: [{
				formatter: 'string',
				console: true,
			}],
			failAfterError: false,
		}))
		.pipe(dest('./src/scss'));
};
```
I'm running gulp v4 and gulp-stylelint ^8.0.0. I just can't seem to figure out why it's not running correctly when the CLI does.

Thanks for the great plugin and any help would be really appricated.
